export const quiz = [
    { question:"日本の首都は？",
      option1:"東京",
      option2:"大阪",
      option3:"京都",
      answer:"東京"
    },
    { question:"地球は何番目の惑星？",
      option1:"１番目",
      option2:"２番目",
      option3:"３番目",
      answer:"３番目"
    },
    { question:"水は何度で凍る？",
      option1:"０度",
      option2:"１０度",
      option3:"１００度",
      answer:"０度"
    },
    { question:"日本の国鳥は？",
      option1:"スズメ",
      option2:"キジ",
      option3:"ツバメ",
      answer:"キジ"
    },
    { question:"日の出はどちらの方角？",
      option1:"西",
      option2:"南",
      option3:"東",
      answer:"東"
    },
    { question:"赤信号の意味は？",
      option1:"進め",
      option2:"止まれ",
      option3:"注意",
      answer:"止まれ"
    },
    { question:"1年は何ヶ月？",
      option1:"10",
      option2:"12",
      option3:"13",
      answer:"12"
    },
    { question:"成人は何歳から？",
      option1:"16歳",
      option2:"18歳",
      option3:"20歳",
      answer:"18歳"
    },
    { question:"日本の紙幣の単位は？",
      option1:"ドル",
      option2:"元",
      option3:"円",
      answer:"円"
    },
    { question:"カレーに使う黄色い粉は？",
      option1:"こしょう",
      option2:"ターメリック",
      option3:"しょうが",
      answer:"ターメリック"
    },
    { question: "日本の首都はどこ？",
			option1: "東京",
			option2: "大阪",
			option3: "京都",
			answer: "東京" 
		},
		{ question: "富士山の高さは？",
			option1: "3776m",
			option2: "3000m",
			option3: "2500m",
			answer: "3776m" 
		},
		{ question: "水の沸点は何度？",
			option1: "100℃",
			option2: "80℃",
			option3: "60℃",
			answer: "100℃" 
		},
		{ question: "犬の鳴き声は？",
			option1: "ワン",
			option2: "ニャー",
			option3: "モー",
			answer: "ワン" 
		},
		{ question: "信号の止まれの色？",
			option1: "赤",
			option2: "青",
			option3: "黄",
			answer: "赤" 
		},
		{ question: "1日は何時間？",
			option1: "24",
			option2: "12",
			option3: "36",
			answer: "24" 
		},
		{ question: "空の色は？",
			option1: "青",
			option2: "赤",
			option3: "緑",
			answer: "青" 
		},
		{ question: "海の色は？",
			option1: "青",
			option2: "白",
			option3: "黒",
			answer: "青" 
		},
		{ question: "日本の国旗の色は？",
			option1: "赤白",
			option2: "青白",
			option3: "黒白",
			answer: "赤白" 
		},
		{ question: "ネコの鳴き声は？",
			option1: "ニャー",
			option2: "ワン",
			option3: "ブー",
			answer: "ニャー" 
		},
		{ question: "野球の球数は？",
			option1: "9回",
			option2: "7回",
			option3: "5回",
			answer: "9回" 
		},
		{ question: "サッカーの人数は？",
			option1: "11人",
			option2: "10人",
			option3: "9人",
			answer: "11人" 
		},
		{ question: "地球は何番目の惑星？",
			option1: "3番目",
			option2: "4番目",
			option3: "5番目",
			answer: "3番目" 
		},
		{ question: "りんごの色は？",
			option1: "赤",
			option2: "青",
			option3: "黄",
			answer: "赤" 
		},
		{ question: "電車は何で動く？",
			option1: "電気",
			option2: "ガス",
			option3: "木材",
			answer: "電気" 
		},
		{ question: "人の骨は何本？",
			option1: "206本",
			option2: "150本",
			option3: "300本",
			answer: "206本" 
		},
		{ question: "お金の単位は？",
			option1: "円",
			option2: "ドル",
			option3: "元",
			answer: "円" 
		},
		{ question: "小学校は何年？",
			option1: "6年",
			option2: "5年",
			option3: "4年",
			answer: "6年" 
		},
		{ question: "時計は何を測る？",
			option1: "時間",
			option2: "距離",
			option3: "重さ",
			answer: "時間" 
		},
		{ question: "地球の衛星は？",
			option1: "月",
			option2: "火星",
			option3: "太陽",
			answer: "月" 
		}
];
